"""Township Canada Python SDK — Canadian legal land description coordinate conversion.

Usage::

    from townshipcanada import TownshipCanada

    tc = TownshipCanada("your_api_key")
    result = tc.search("NW-36-42-3-W5")
    print(result.latitude, result.longitude)
"""

from .client import AsyncTownshipCanada, TownshipCanada
from .exceptions import (
    AuthenticationError,
    NotFoundError,
    PayloadTooLargeError,
    RateLimitError,
    ServerError,
    TownshipCanadaError,
    ValidationError,
)
from .models import (
    AgBatchItem,
    AgBatchResponse,
    AgCropping,
    AgDominantCrop,
    AgDrought,
    AgHydrology,
    AgHydrologyFeature,
    AgLandUse,
    AgLandUseBreakdown,
    AgLandUseClass,
    AgMunicipality,
    AgNearestFeature,
    AgParcel,
    AgParcelContext,
    AgProductivity,
    AgProductivityRating,
    AgProvincialDetail,
    AgReport,
    AgSoil,
    AgSoilClassification,
    AgWetlands,
    AutocompleteSuggestion,
    BatchItemError,
    BatchMeta,
    BatchResult,
    EnergyBatchItem,
    EnergyBatchResponse,
    EnergyDominantOperator,
    EnergyFacilitiesSection,
    EnergyFacilityRow,
    EnergyOperator,
    EnergyParcel,
    EnergyPipelineRow,
    EnergyPipelinesSection,
    EnergyProduction,
    EnergyProductionVolumes,
    EnergyReport,
    EnergySummary,
    EnergySummaryFacilities,
    EnergySummaryOperators,
    EnergySummaryPipelines,
    EnergySummaryWells,
    EnergyTenureRow,
    EnergyTenureSection,
    EnergyWellCounts,
    EnergyWellRow,
    EnergyWellsSection,
    Feature,
    FeatureCollection,
    FeatureProperties,
    LatLng,
    MultiPolygon,
    OperatorRef,
    Point,
    Polygon,
    ReportMeta,
    SearchResult,
    SectionSource,
    UnavailableSection,
)

__all__ = [
    "TownshipCanada",
    "AsyncTownshipCanada",
    "TownshipCanadaError",
    "AuthenticationError",
    "NotFoundError",
    "PayloadTooLargeError",
    "RateLimitError",
    "ServerError",
    "ValidationError",
    "SearchResult",
    "BatchResult",
    "AutocompleteSuggestion",
    "FeatureCollection",
    "Feature",
    "FeatureProperties",
    "Point",
    "Polygon",
    "MultiPolygon",
    "LatLng",
    "OperatorRef",
    "ReportMeta",
    "SectionSource",
    "UnavailableSection",
    "BatchItemError",
    "BatchMeta",
    "AgReport",
    "AgBatchItem",
    "AgBatchResponse",
    "AgParcel",
    "AgProductivity",
    "AgProductivityRating",
    "AgCropping",
    "AgDominantCrop",
    "AgSoil",
    "AgSoilClassification",
    "AgLandUse",
    "AgLandUseClass",
    "AgLandUseBreakdown",
    "AgDrought",
    "AgWetlands",
    "AgHydrology",
    "AgHydrologyFeature",
    "AgMunicipality",
    "AgNearestFeature",
    "AgParcelContext",
    "AgProvincialDetail",
    "EnergyReport",
    "EnergyBatchItem",
    "EnergyBatchResponse",
    "EnergyParcel",
    "EnergySummary",
    "EnergySummaryWells",
    "EnergySummaryPipelines",
    "EnergySummaryFacilities",
    "EnergySummaryOperators",
    "EnergyWellCounts",
    "EnergyDominantOperator",
    "EnergyProduction",
    "EnergyProductionVolumes",
    "EnergyTenureRow",
    "EnergyTenureSection",
    "EnergyWellRow",
    "EnergyWellsSection",
    "EnergyPipelineRow",
    "EnergyPipelinesSection",
    "EnergyFacilityRow",
    "EnergyFacilitiesSection",
    "EnergyOperator",
]

from importlib.metadata import version as _pkg_version

try:
    __version__ = _pkg_version("townshipcanada")
except Exception:
    __version__ = "0.0.0-dev"
